queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>1"

pull_request_rules:
  - name: automerge to develop with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base=develop
      - label=automerge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: frontport patches to develop branch
    conditions:
      - base=main
      - label=frontport/develop
    actions:
      backport:
        branches:
          - develop
  - name: backport patches to main branch
    conditions:
      - base=develop
      - label=backport/main
    actions:
      backport:
        branches:
          - main
