source_chain: quicktest-1
source_lcd: https://lcd.dev.quicksilver.zone
chains:
  quickgaia-1: http://dev01.quicksilver.zone:21401
  quickstar-1: http://dev01.quicksilver.zone:22401
  quickosmo-1: http://dev01.quicksilver.zone:23101
