source_chain: rhye-2
source_lcd: https://lcd.test.quicksilver.zone
chains:
  provider: https://rpc.provider.test.quicksilver.zone:443
  elgafar-1: https://rpc.elgafar-1.test.quicksilver.zone:443
  osmo-test-5: https://rpc.osmo-test-5.test.quicksilver.zone:443
  regen-redwood-1: https://rpc.regen-redwood-1.test.quicksilver.zone:443
  rhye-2: https://rpc.test.quicksilver.zone:443
