FROM rust:1.72 as build
ARG VERSION

RUN apt update && apt install git -y

WORKDIR /app/src

RUN git clone https://github.com/informalsystems/ibc-rs --branch $VERSION

WORKDIR ibc-rs

RUN cargo build --release

FROM debian:bullseye-slim

RUN apt update && apt install ca-certificates -y
COPY --from=build /app/src/ibc-rs/target/release/hermes /usr/local/bin/hermes
RUN adduser --system --home /hermes --disabled-password --disabled-login hermes -u 1000
USER hermes

