name: Deploy to GitHub Pages

on:
  push:
    branches:
      - bunDev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or specify a version

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Export Project
        run: bun export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
