name: Build Web UI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Run install for quicksilverjs
        run: | 
            cd web-ui
            yarn install
            
      - name: Build production bundle for quicksilverjs
        run: |
            cd web-ui
            yarn build 
