on:
  push:
    paths:
      - xcclookup/**
  pull_request:
    paths:
      - xcclookup/**

name: xcclookup
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.5]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: xcclookup/go.sum
      - run: |
          cd xcclookup
          go test ./...
  build:
    strategy:
      matrix:
        go-version: [1.24.5]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: xcclookup/go.sum
      - run: |
          cd xcclookup
          make build
